<a href="https://colab.research.google.com/github/rohan-vr/lets-upgrade-ds101/blob/main/assignment-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
import numpy as np
arr=np.array([i for i in range(2,51,3)])
print(arr)
print(type(arr)) # to check if its numpy or not

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


2) Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [15]:
import numpy as np

done=False

while not done:
  
  list_1=list(map(int, input().split()))
  list_2=list(map(int, input().split()))

  if len(list_1)==5 and len(list_2)==5:
    done=True
  else:
    print('Please enter 5 numbers')
    done=False

array_1 = np.array(list_1)
array_2 = np.array(list_2)

final_array=np.concatenate((array_1, array_2))
print('Concatinated array is: ',final_array)

print('Sorted array1 is: ',np.sort(array_1))
print('Sorted array2 is: ',np.sort(array_2))

1 100 2 99 3
10 9 8 7 6
Concatinated array is:  [  1 100   2  99   3  10   9   8   7   6]
Sorted array1 is:  [  1   2   3  99 100]
Sorted array2 is:  [ 6  7  8  9 10]


3) Write a code snippet to find the dimensions of a ndarray and its size.

In [18]:
import numpy as np

arr=np.array([[3,4],[1,2]])
print(arr.shape, arr.size) # shape returns dimension, size returns size

(2, 2) 4


4) How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [20]:
import numpy as np

arr=np.array([1,2,3])
print(arr.shape) # to check if its 1D

new_arr=arr[np.newaxis, :]
print(new_arr.shape) # became a 2D array

(3,)
(1, 3)


5) Consider two square numpy arrays. Stack them vertically and horizontally.

In [22]:
import numpy as np

array1=np.array([[1,2], [3,4]])
array2=np.array([[5,6], [7,8]])

print(np.vstack((array1, array2))) # vertical stack
print(np.hstack((array1, array2))) # horizontal stack

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


6) How to get unique items and counts of unique items?

In [24]:
from collections import Counter

items=['Apple', 'Orange', 'Apple', 'Banana', 'Orange', 'Orange', 'Apple', 'Banana']

unique_items=set(items) # set does not accept duplicate items 

count=Counter(items) # inbuilt dictionary function for counting

for item in unique_items:
  print(item, count[item])

Banana 2
Apple 3
Orange 3
